---
apiVersion: v1
kind: Service
metadata:
  name: community-service
  labels:
    app: community-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: community-service

