apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gw
  labels:
    app: api-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      labels:
        app: api-gw
    spec:
      containers:
        - name: api-gw
          image: quay.io/danielmunro/otto-api-gw:latest
          ports:
            - containerPort: 8000
          env:
            - name: TARGET_COMMUNITY_SERVICE
              value: community-service:8081
            - name: TARGET_USER_SERVICE
              value: user-service:8080
            - name: TARGET_IMAGE_SERVICE
              value: image-service:8082
            - name: TARGET_UI
              value: ui:3000

