apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: quay.io/danielmunro/otto-image-service:latest
          resources:
            requests:
              ephemeral-storage: "500Mi"
            limits:
              ephemeral-storage: "500Mi"
          ports:
            - containerPort: 8082
          env:
            - name: USER_SERVICE_HOST
              value: "$(USER_SERVICE_SERVICE_HOST):8080"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: aws_secret_access_key
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: db_host
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: db_user
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: db_port
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: db_password
            - name: PG_DBNAME
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: db_name
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: kafka_host
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: s3_region
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: image-config
                  key: s3_bucket
