apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: quay.io/danielmunro/otto-image-service:latest
          resources:
            requests:
              ephemeral-storage: "500Mi"
            limits:
              ephemeral-storage: "500Mi"
          ports:
            - containerPort: 8082
          env:
            - name: USER_SERVICE_HOST
              value: "$(USER_SERVICE_SERVICE_HOST):8080"
            - name: KAFKA_HOST
              value: "$(KAFKA_SERVICE_HOST):9092"
